CREATE TABLE IF NOT EXISTS stocks (
    id SERIAL PRIMARY KEY,
    sku BIGINT UNIQUE NOT NULL,
    quantity INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

